# Generated by Django 5.2.4 on 2025-07-24 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام سنگ')),
                ('scientific_name', models.CharField(blank=True, max_length=150, verbose_name='نام علمی')),
                ('stone_type', models.CharField(choices=[('igneous', 'آذرین'), ('sedimentary', 'رسوبی'), ('metamorphic', 'دگرگونی')], max_length=50, verbose_name='نوع سنگ')),
                ('colors', models.CharField(blank=True, max_length=100, verbose_name='رنگ\u200cها')),
                ('hardness', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='سختی (مقیاس موس)')),
                ('density', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='چگالی (g/cm³)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('applications', models.TextField(blank=True, verbose_name='کاربردها')),
                ('extraction_sites', models.TextField(blank=True, verbose_name='محل\u200cهای استخراج')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_stones/', verbose_name='تصویر')),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت هر کیلوگرم')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='مقدار موجود')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'محصول سنگ',
                'verbose_name_plural': 'محصولات سنگ',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قیمت کل')),
                ('status', models.CharField(choices=[('paid', 'پرداخت شده'), ('pending', 'در انتظار پرداخت'), ('failed', 'پرداخت نشده')], default='pending', max_length=10, verbose_name='وضعیت سفارش')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productstone', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
