# Generated by Django 5.2.4 on 2025-07-24 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سنگ')),
                ('stone_type', models.CharField(choices=[('igneous', 'آذرین'), ('sedimentary', 'رسوبی'), ('metamorphic', 'دگرگونی')], max_length=50, verbose_name='نوع سنگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('main_color', models.CharField(blank=True, max_length=50, verbose_name='رنگ اصلی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stones/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'سنگ',
                'verbose_name_plural': 'سنگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='StoneComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='نام نویسنده')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='general.stone')),
            ],
        ),
        migrations.CreateModel(
            name='StoneFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='general.stone')),
            ],
        ),
    ]
