# Generated by Django 5.2.4 on 2025-07-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stone',
            options={'verbose_name': 'stone', 'verbose_name_plural': 'stones'},
        ),
    ]
