# Generated by Django 5.2.4 on 2025-07-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_stone_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stonefaq',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ'),
        ),
    ]
